included:
    - CocoaHeadsNL

excluded:
    - Pods
    - Frameworks
    - bin
    - Build-Phases
    - Products

opt_in_rules:
# 0ï¸âƒ£ - Geen meerwaarde
# 1ï¸âƒ£ - Minimale meerwaarde
# 2ï¸âƒ£ - Gemiddelde meerwaarde
# 3ï¸âƒ£ - Hoge meerwaarde
# 4ï¸âƒ£ - No-brainers
# ðŸš— - supports autocorrect
# âš ï¸ - Number of warnings

# Stylistic Rules ðŸ’…ðŸ»
# - let_var_whitespace # 1ï¸âƒ£ âš ï¸ 434, Zorg ervoor dat in variable en een functie niet tegen elkaar aanstaan (protocols) style
- operator_usage_whitespace # 1ï¸âƒ£ ðŸš— dubbele spaties, missende spaties
- closure_end_indentation # 1ï¸âƒ£ ðŸš—, { } closures
- closure_parameter_position # 1ï¸âƒ£, { text within closures  }
# - collection_alignment # 1ï¸âƒ£ âš ï¸ 3, 3 regels code die niet netjes uitgelijnd zijn.
# - conditional_returns_on_newline # 1ï¸âƒ£ âš ï¸ 2, # only for -if statements
# - function_default_parameter_at_end # 1ï¸âƒ£ âš ï¸ 10, #in functies worden default parameters aan het einde gezet: func bla(foo: String, roo: Int = 200)
# - multiline_arguments # 1ï¸âƒ£ âš ï¸ 49, Of alle argumenten van een functie in 1 regel of alle argumenten per regel en niet 3 argumenten op regel 1 en 4 argumenten op regel 2
- multiline_parameters # 1ï¸âƒ£, parameters of allemaal op 1 regel of per regel een parameter
# - multiline_function_chains # 1ï¸âƒ£ âš ï¸ 129, chaining op meerdere regels, zorgt voor structuur
# - multiline_parameters_brackets # 1ï¸âƒ£ âš ï¸ 10,
- closure_spacing # 2ï¸âƒ£ ðŸš—, spacing tussen clusures zorgt voor veel spatie irritatie

# Hygienic Rules ðŸ§»
# - file_header # 0ï¸âƒ£, âš ï¸ 688 warnings
# - closure_body_length # 1ï¸âƒ£ âš ï¸ 8, Teveel logica in een closure  () -- Emiel
- explicit_init # 1ï¸âƒ£ ðŸš—, Compleet overbodig om init aan te roepen voor bijvoorbeeld: UIColor.init(hexcode: "5288f5") ipv UIColor(hexcode: "5288f5"
# - toggle_bool # 1ï¸âƒ£ âš ï¸ 2, someBool.toggle() over someBool = !someBool.
- unused_import # 1ï¸âƒ£ ðŸš—
- unneeded_parentheses_in_closure_argument # 3ï¸âƒ£ ðŸš—,
- redundant_type_annotation # 1ï¸âƒ£ ðŸš—, let storyBoard: UIStoryboard = UIStoryboard("")
# - empty_string # 4ï¸âƒ£ âš ï¸ 9 performance verbetering wanneer we aString.isEmpty gebruiken ipv aString == ""
# - first_where # 4ï¸âƒ£ âš ï¸ 5 performance verbetering Prefer using .first(where:) over .filter { }.first in collections.
- last_where # 4ï¸âƒ£ performance, zelfde als first_where
# - sorted_first_last # 4ï¸âƒ£ âš ï¸ 5 performance, gebruik maken van min/max functies van array's ipv sorteren en vervolgens .first/.last

# Convention Rules ðŸ¤
- modifier_order # 1ï¸âƒ£ ðŸš— âš ï¸ 17, style, 'class private func' moet worden 'private class func'
# - no_grouping_extension # 1ï¸âƒ£ âš ï¸ 477, style, persoonelijk vind ik het niet logisch dat een class geextend wordt om daarin code te groeperen (alleen intereresant voor class extensies zonder dat ze ook een protocol inmplementeren)
# - legacy_random # 2ï¸âƒ£ âš ï¸ 1, random is vernieuwd
# - fatal_error_message # 2ï¸âƒ£ âš ï¸ 72, Helpt de andere developers, kleine moeite https://medium.com/@abhimuralidharan/what-are-fatal-errors-and-when-to-use-them-53ad1a66c6d6
# - convenience_type # 3ï¸âƒ£ âš ï¸ 60, structs, classes en enums die verkeerd gebruikt worden (classes die geen struct zijn) En dit heeft invloed op de performance waarom: https://stackoverflow.com/a/24232845/2826164
- prohibited_super_call
- override_in_extension
- unused_optional_binding
- yoda_condition

# Code Smells Rules ðŸ’©
# - force_unwrapping # 3ï¸âƒ£ âš ï¸ 147, force unwrapping can cause crashes (is nu ook al een ongeschreven regel)
# - implicitly_unwrapped_optional # 3ï¸âƒ£ âš ï¸ 96, avoid force unwrap
- redundant_nil_coalescing # 2ï¸âƒ£ ðŸš— âš ï¸ 3, var myVar: Int? = nil; myVar ?? nil
# - contains_over_first_not_nil # 2ï¸âƒ£ âš ï¸ 4, performance verbetering
# - pattern_matching_keywords # 3ï¸âƒ£ âš ï¸ 8,  case let .foo(x, y): break  ipv  case .foo(â†“let x, â†“let y): break

# Bug Avoiding Rules ðŸž
- fallthrough # 2ï¸âƒ£ switch falltrough zorgt voor onduidelijkheid, wordt gelukkig nergens gebruikt!  Kan Aan!
- no_fallthrough_only
# - lower_acl_than_parent # 2ï¸âƒ£ âš ï¸ 292, onduidelijkheid: accesss van functies en variabelen die meer toegangkelijkheid bieden hebben dan de klasse
# - no_extension_access_modifier # 2ï¸âƒ£ âš ï¸ 25, extensions horen niet het toegangsniveau aan te passen bijv: (private extension String)
# - private_action # 3ï¸âƒ£ âš ï¸ 47, voorkomt om deze actions via een andere manier aan te roepen
# - private_outlet # 3ï¸âƒ£ âš ï¸ 153, voorkomt om deze outlets via een andere klasse aangepast kunnen worden
# - strong_iboutlet # 3ï¸âƒ£ âš ï¸ 341, kan crashes voorkomen als de view die de outlet bevat verdwijnt https://cocoacasts.com/should-outlets-be-weak-or-strong
# - overridden_super_call  # 3ï¸âƒ£ âš ï¸ 24, inpact onbekend, lijkt me goed om uit te zoeken
# - file_name  # 4ï¸âƒ£ 26 âš ï¸, met honderden bestanden is het belangrijk dat de "Bestandsnaam.swift" overeen komt met de klassenaam "Bestandennaam"
- empty_count # 4ï¸âƒ£, performance verbetering wanneer we count > 0 vervangen met isEmpty

disabled_rules:
    - trailing_newline
    - trailing_whitespace

    # regels om aan te zetten:
    - large_tuple # Aanzetten, gebruik een struct of een class (max 3)
    - function_parameter_count # aanzetten, functies met meer dan 5 counts kunnen in de praktijk gewoon een struct of een class als parameter mee krijgen en dan daarnaar handelen


type_name:
    min_length: 3
    max_length: 70

# min_length op 3 met uitzondering voor Id
identifier_name:
    min_length: 1
    max_length: 60
    allowed_symbols: "_"

file_length:
  warning: 901
  error: 900 # files boven de 900 regels zijn error's

conditional_returns_on_newline:
  if_only: true

# Langste functie is 174 regels+ . het is belangrijk dat verantwoordelijkheid in functies wordt opgesplitst
# 50 regels maximaal liever korter. Voor te lange functies is // swiftlint:disable:next function_body_length
function_body_length:
    warning: 50
    error: 50

large_tuple:
  warning: 3

# Geen idee of hier enige waarde aan gehecht wordt, regellengte (emiel says: 'no')
# Xcode, Settings, Text Editing, indention tab, 'Check linewrapping' om lengte van regel irritatie te voorkomen.
line_length:
    warning: 301
    error: 300
    ignores_comments: true

file_header:
  required_pattern: |
                  \/\/
                  \/\/  .*?\.swift
                  \/\/  EvenAppen
                  \/\/
                  \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                  \/\/  Copyright Â© \d{4} Achmea\. All rights reserved\.
                  \/\/

reporter: "xcode"
